objects =
{
  plane = {
	  texture = "shadow",
	  model = "plane.obj",
	  position = { x = 0, y = 0.9, z = 0,},
	  scale = { x = 1, y = 1, z = 1, },
      rotation = { x = 0, y = 0, z = 0,},
  },
  desk = {
  	  texture = "DeskBase.png",
	  model = "Desk.obj",
	  position = { x = 0, y = -0.5, z = 0,},
	  scale = { x = 3, y = 3, z = 3, },
      rotation = { x = 0, y = 0, z = 0,},
  },
  chair = {
  	  texture = "ChairBase.png",
	  model = "Chair.obj",
	  position = { x = 0.5, y = 0.3 , z = 2.6 ,},
	  scale = { x = 3, y = 3, z = 3,},
      rotation = { x = 0, y = -135, z = 0,},
  },
  folders = {
  	  texture = "FoldersBase.png",
	  model = "Folders.obj",
	  position = { x = -2.18 , y = -1.185 , z = 1.55 ,},
	  scale = { x = 3, y = 3, z = 3,},
      rotation = { x = 0, y = 180, z = 0,},
  },
  desklamp = {
  	  texture = "DeskLampBase.png",
	  model = "DeskLamp.obj",
	  position = { x = 2.25 , y = 1.6 , z = -0.9 ,},
	  scale = { x = 3, y = 3, z = 3,},
      rotation = { x = 0, y = -42, z = 0,},
  },
  clipboard = {
  	  texture = "ClipboardBase.png",
	  model = "Clipboard.obj",
	  position = { x = 1 , y = 0.9 , z = 0.09 ,},
	  scale = { x = 3, y = 3, z = 3,},
      rotation = { x = 0, y = -11.7, z = 0,},
  },
 ashtray = {
  	  texture = "AshtrayBase.png",
	  model = "Ashtray.obj",
	  position = { x = 2.95 , y = -0.3 , z = 1.7,},
	  scale = { x = 3, y = 3, z = 3,},
      rotation = { x = 0, y = -11.7, z = 0,},
  },
  revolver = {
  	  texture = "RevolverBase.png",
	  model = "Revolver.obj",
	  position = { x = -2.16 , y = 0.92 , z = 0.3,},
	  scale = { x = 3, y = 3, z = 3,},
      rotation = { x = 98.5, y = 201, z = 150,},
  },
  whiskeybottle = {
  	  texture = "BottleBase.png",
	  model = "WhiskeyBottle.obj",
	  position = { x = -2.2 , y = 1.44 , z = -0.55 ,},
	  scale = { x = 3, y = 3, z = 3,},
      rotation = { x = 0, y = 26, z = 0,},
  },
  cigarbox = {
  	  texture = "BoxBase.png",
	  model = "CigarBox.obj",
	  position = { x = 2.035 , y = 1.074 , z = 0.115 ,},
	  scale = { x = 3, y = 3, z = 3,},
      rotation = { x = 0, y = -7, z = 0,},
  },
  pen = {
  	  texture = "PenBaseGold.png",
	  model = "Pen.obj",
	  position = { x = 0.9 , y = 0.9 , z = 0,},
	  scale = { x = 3, y = 3, z = 3,},
      rotation = { x = 0, y = -25, z = 108,},
  },
  wall = {
  	  texture = "WallTextureRGB.png",
	  model = "Wall.obj",
	  position = { x = 0 , y = 2.7 , z = -2.2,},
	  scale = { x = 1, y = 1, z = 1,},
      rotation = { x = 0, y = 90, z = 0,},
  },
  floor = {
  	  texture = "OfficeFloorTexture.png",
	  model = "plane20x20_2048tris_aligned_uvs.obj",
	  position = { x = 0, y = -2, z = 0},
	  scale = { x = 1.5, y = 1.5, z = 1.5, },
      rotation = { x = 0, y = 0, z = 0,},
  },
}
