objects =
{
  plane = {
	  texture = "shadow",
	  model = "plane.obj",
	  position = { x = 0, y = 0.9, z = 0.5,},
	  scale = { x = 1, y = 1, z = 1, },
      rotation = { x = 0, y = 0, z = 0,},
  },
  desk = {
  	  texture = "DeskBase.png",
	  model = "Desk.obj",
	  position = { x = 0, y = -0.5, z = 0,},
	  scale = { x = 3, y = 3, z = 3, },
      rotation = { x = 0, y = 0, z = 0,},
  },
  chair = {
  	  texture = "ChairBase.png",
	  model = "Chair.obj",
	  position = { x = 0.5, y = 0.3 , z = 2.6 ,},
	  scale = { x = 3, y = 3, z = 3,},
      rotation = { x = 0, y = -135, z = 0,},
  },
  folders = {
  	  texture = "FoldersBase.png",
	  model = "Folders.obj",
	  position = { x = -2.18 , y = -1.185 , z = 1.55 ,},
	  scale = { x = 3, y = 3, z = 3,},
      rotation = { x = 0, y = 180, z = 0,},
  },
  --desklamp = {
  	-- texture = "DeskLampBase.png",
	  --model = "DeskLamp.obj",
	  --position = { x = 2.25 , y = 1.6 , z = -0.9 ,},
	  --scale = { x = 3, y = 3, z = 3,},
      --rotation = { x = 0, y = -42, z = 0,},
  --},
  clipboard = {
  	  texture = "ClipboardBase.png",
	  model = "Clipboard.obj",
	  position = { x = 1.2 , y = 0.9 , z = 0.09 ,},
	  scale = { x = 3, y = 3, z = 3,},
      rotation = { x = 0, y = -11.7, z = 0,},
  },
 ashtray = {
  	  texture = "AshtrayBase.png",
	  model = "Ashtray.obj",
	  position = { x = 6.3 , y = -0.3 , z = 1.7,},
	  scale = { x = 3, y = 3, z = 3,},
      rotation = { x = 0, y = -11.7, z = 0,},
  },
  revolver = {
  	  texture = "RevolverBase.png",
	  model = "Revolver.obj",
	  position = { x = -2 , y = 0.92 , z = 0.5,},
	  scale = { x = 3, y = 3, z = 3,},
      rotation = { x = 100, y = -186, z = -116,},
  },
  whiskeybottle = {
  	  texture = "BottleBase.png",
	  model = "WhiskeyBottle.obj",
	  position = { x = -2.2 , y = 1.44 , z = -0.55 ,},
	  scale = { x = 3, y = 3, z = 3,},
      rotation = { x = 0, y = 26, z = 0,},
  },
  cigarbox = {
  	  texture = "BoxBase.png",
	  model = "CigarBox.obj",
	  position = { x = 2.235 , y = 1.074 , z = 0.115 ,},
	  scale = { x = 3, y = 3, z = 3,},
      rotation = { x = 0, y = -30, z = 0,},
  },
  pen = {
  	  texture = "PenBaseBlack.png",
	  model = "Pen.obj",
	  position = { x = 0.9 , y = 0.9 , z = 0,},
	  scale = { x = 3, y = 3, z = 3,},
      rotation = { x = 0, y = -25, z = 108,},
  },
  wall = {
  	  texture = "WallTexturegreen2RGB.png",
	  model = "Wall.obj",
	  position = { x = 0 , y = 2.7 , z = -2.2,},
	  scale = { x = 3, y = 3, z = 3,},
      rotation = { x = 0, y = 90, z = 0,},
  },
  floor = {
  	  texture = "OfficeFloorTexture.png",
	  model = "plane20x20_2048tris_aligned_uvs.obj",
	  position = { x = 0, y = -2, z = 0},
	  scale = { x = 1.5, y = 1.5, z = 1.5, },
      rotation = { x = 0, y = 0, z = 0,},
  },
  bookshelf = {
  	  texture = "BookCaseTexture2.png",
	  model = "bookshelf.obj",
	  position = { x = -1, y = 1.8, z = -2,},
	  scale = { x = 1.8, y = 1.8, z = 1.8,},
      rotation = { x = 0, y = 90, z = 0,},
  },
    wallframes = {
  	  texture = "WallFramesTexture.png",
	  model = "WallFrames.obj",
	  position = { x = 2 , y = 2, z = -2,},
	  scale = { x = 1.5, y = 1.5, z = 1.5,},
      rotation = { x = 0, y = 90, z = 0,},
  },
      Pinboard = {
  	  texture = "PinBoardtexture.png",
	  model = "PinBoard.obj",
	  position = { x = 0, y = 3, z = -2.2,},
	  scale = { x = 0.115, y = 0.15, z = 0.16,},
      rotation = { x = 90, y = 90, z = 0,},
  },
      Cork = {
  	  texture = "marisading.png",
	  model = "plane.obj",
	  position = { x = -0.002, y = 2.995, z = -2.18,},
	  scale = { x = 0.92, y = 0.69, z = 0.65,},
      rotation = { x = 90, y = 0, z = 0,},
  },
    Phone = {
  	  texture = "PhoneBase.png",
	  model = "Phone.obj",
	  position = { x = -1.5 , y = 1.2 , z = -1,},
	  scale = { x = 3, y = 3, z = 3,},
      rotation = { x = 0, y = 25, z = 0,},
  },
    folders2 = {
  	  texture = "FoldersBase.png",
	  model = "Folders.obj",
	  position = { x = 2 , y = 1.1 , z = -1.2 ,},
	  scale = { x = 3, y = 3, z = 3,},
      rotation = { x = 90, y = 0, z = 2,},
  },
}
